// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.28.3
// source: strategy/plugin/proto/strategy/v1/strategy.proto

package strategy

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type ExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExecuteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The reply message containing the greetings
type ExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The greeting service definition.
// go:plugin type=plugin version=1
type StrategyService interface {
	// Sends a greeting
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
}
