//go:build tinygo.wasm

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.28.3
// source: strategy/plugin/proto/strategy/v1/strategy.proto

package strategy

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
)

const StrategyServicePluginAPIVersion = 1

//export strategy_service_api_version
func _strategy_service_api_version() uint64 {
	return StrategyServicePluginAPIVersion
}

var strategyService StrategyService

func RegisterStrategyService(p StrategyService) {
	strategyService = p
}

//export strategy_service_execute
func _strategy_service_execute(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(ExecuteRequest)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := strategyService.Execute(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
