name: Build examples
on: [push]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      # Check out the repository
        - uses: actions/checkout@v4
      # Run Docker Compose Action
        - name: Build dispatcher example
          uses: adambirds/docker-compose-action@v1.5.0
          env:
            OPENAI_TOKEN: "fake token"
          with:
            compose-file: "./examples/dispatcher/docker-compose.yaml"
            up-flags: "--build --no-start"